if(POLICY CMP0011)
    cmake_policy(SET CMP0011 NEW)
endif()

if(NOT DEFINED BUILD_DIR)
    message(FATAL_ERROR "BUILD_DIR is required")
endif()

if(NOT DEFINED DEPFILE)
    set(DEPFILE "${BUILD_DIR}/agrb_shaders.d")
endif()

if(NOT DEFINED STAMP_FILE)
    set(STAMP_FILE "${BUILD_DIR}/.spv.stamp")
endif()

function(_shader_unescape _input _output)
    string(REPLACE "\\ " "__AGRBSH_SPACE__" _tmp "${_input}")
    string(REPLACE "__AGRBSH_SPACE__" " " _tmp "${_tmp}")
    set(${_output} "${_tmp}" PARENT_SCOPE)
endfunction()

function(_shader_collect_files _line _suffix _out_var)
    string(REGEX REPLACE " +" ";" _tokens "${_line}")
    set(_out "")
    foreach(_tok IN LISTS _tokens)
        if(_tok STREQUAL "")
            continue()
        endif()
        _shader_unescape("${_tok}" _tok_unescaped)
        if(_tok_unescaped MATCHES "${_suffix}$")
            list(APPEND _out "${_tok_unescaped}")
        endif()
    endforeach()
    set(${_out_var} "${_out}" PARENT_SCOPE)
endfunction()

function(_shader_dep_needs_rebuild _target _deps _out_var)
    set(_needs FALSE)
    if(NOT EXISTS "${_target}")
        set(_needs TRUE)
    else()
        file(TIMESTAMP "${_target}" _target_ts UTC)
        foreach(_dep IN LISTS _deps)
            if(NOT EXISTS "${_dep}")
                set(_needs TRUE)
                break()
            endif()
            file(TIMESTAMP "${_dep}" _dep_ts UTC)
            if(_dep_ts STRGREATER _target_ts)
                set(_needs TRUE)
                break()
            endif()
        endforeach()
    endif()
    set(${_out_var} "${_needs}" PARENT_SCOPE)
endfunction()

if(NOT EXISTS "${DEPFILE}")
    message(FATAL_ERROR "Shader depfile not found: ${DEPFILE}")
endif()

file(STRINGS "${DEPFILE}" _dep_lines)
set(_compiled_count 0)

foreach(_line IN LISTS _dep_lines)
    if(_line STREQUAL "")
        continue()
    endif()
    if(NOT _line MATCHES "\\.spv(\\.cmd)?:")
        continue()
    endif()

    string(FIND "${_line}" ": " _split_pos)
    if(_split_pos EQUAL -1)
        continue()
    endif()

    string(SUBSTRING "${_line}" 0 ${_split_pos} _targets_raw)
    math(EXPR _deps_start "${_split_pos} + 2")
    string(SUBSTRING "${_line}" ${_deps_start} -1 _deps_raw)

    _shader_collect_files("${_targets_raw}" "\\.spv" _spv_targets)
    _shader_collect_files("${_targets_raw}" "\\.spv\\.cmd" _cmd_targets)
    if(NOT _spv_targets OR NOT _cmd_targets)
        continue()
    endif()

    list(GET _spv_targets 0 _spv_file)
    list(GET _cmd_targets 0 _cmd_file)

    string(REGEX REPLACE " +" ";" _dep_tokens "${_deps_raw}")
    set(_deps_list)
    foreach(_dep IN LISTS _dep_tokens)
        if(_dep STREQUAL "")
            continue()
        endif()
        _shader_unescape("${_dep}" _dep_unescaped)
        list(APPEND _deps_list "${_dep_unescaped}")
    endforeach()
    list(APPEND _deps_list "${_cmd_file}")

    _shader_dep_needs_rebuild("${_spv_file}" "${_deps_list}" _needs_rebuild)
    if(NOT _needs_rebuild)
        continue()
    endif()

    file(STRINGS "${_cmd_file}" _cmd_lines)
    set(_cmd_line "")
    foreach(_cmd_entry IN LISTS _cmd_lines)
        string(STRIP "${_cmd_entry}" _cmd_entry_stripped)
        if(_cmd_entry_stripped STREQUAL "")
            continue()
        endif()
        if(_cmd_entry_stripped MATCHES "^[ \t]*@echo[ \t]+off[ \t]*$")
            continue()
        endif()
        set(_cmd_line "${_cmd_entry_stripped}")
    endforeach()
    message(STATUS "Running shader command: ${_cmd_line}")

    if(WIN32)
        execute_process(
            COMMAND cmd /C call "${_cmd_file}"
            RESULT_VARIABLE _cmd_result
        )
    else()
        execute_process(
            COMMAND sh "${_cmd_file}"
            RESULT_VARIABLE _cmd_result
        )
    endif()

    if(NOT _cmd_result EQUAL 0)
        message(FATAL_ERROR "Shader compile command failed: ${_cmd_file}")
    endif()

    math(EXPR _compiled_count "${_compiled_count} + 1")
endforeach()

# Update stamp only when something actually changed (or during first build).
if(_compiled_count GREATER 0 OR NOT EXISTS "${STAMP_FILE}")
    file(TOUCH "${STAMP_FILE}")
endif()
